# .github/workflows/deploy.yml
name: Deploy Next.js to Cloud Run
on:
  push:
    branches:
      - master

env:
  GCP_PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: "us-central1"
  SA_KEY_JSON: ${{ secrets.GCR_SA_KEY }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate GCP
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up gcloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Configure docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Create env file
        run: |
          touch .env
          echo 'MONGODB_URI="${{ secrets.MONGODB_URI }}"' >> .env

      - name: Build next image
        run: npm run build

      - name: Push to Google Container Registry
        run: docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/docker-repository/test-generator-app:${{ github.sha }}

      # Build and push image to Google Container Registry
      - name: Build & Push
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
        working-directory: .docker

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
