# .github/workflows/deploy.yml
name: Deploy Next.js to Cloud Run
on:
  push:
    branches:
      - master

env:
  GCP_PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  CLOUD_RUN_SA: cloud-run@test-generator-2.iam.gserviceaccount.com

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo 'MONGODB_URI="${{ secrets.MONGODB_URI }}"' >> .env

      - name: Build docker image
        run: docker build ./ -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/docker-repository/homepage-for-my-dog:${{ github.sha }}

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      # Build and push image to Google Container Registry
      - name: Build & Push
        run: |-
          gcloud builds submit \
            --quiet \
            --tag gcr.io/$PROJECT_ID/homepage-for-my-dog \
            -- project $PROJECT_ID

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image gcr.io/$PROJECT_ID/homepage-for-my-dog \
            --project PROJECT-ID
            --platform "managed" \
            --allow-unauthenticated
